version: '3.2'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    restart: always

  app_0:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXTCLOUD_BASE_IMAGE: nextcloud:${NEXTCLOUD_VERSION}
    image: jakubkrzywda/nextcloud:${NEXTCLOUD_VERSION}
    restart: always
    ports:
      - "8080:80"
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - nextcloud.env
      - db.env
      - redis.env
      - s3.env
      - gss.env
      - mail.env
    environment:
      - VIRTUAL_HOST=worker0.nx1.dev.nextcloud.safedc.services,nx1.dev.nextcloud.safedc.services
      - LETSENCRYPT_HOST=worker0.nx1.dev.nextcloud.safedc.services,nx1.dev.nextcloud.safedc.services
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default

  app_1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXTCLOUD_BASE_IMAGE: nextcloud:${NEXTCLOUD_VERSION}
    image: jakubkrzywda/nextcloud:${NEXTCLOUD_VERSION}
    restart: always
    ports:
      - "8081:80"
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - nextcloud.env
      - db.env
      - redis.env
      - s3.env
      - gss.env
      - mail.env
    environment:
      - VIRTUAL_HOST=worker1.nx1.dev.nextcloud.safedc.services,nx1.dev.nextcloud.safedc.services
      - LETSENCRYPT_HOST=worker1.nx1.dev.nextcloud.safedc.services,nx1.dev.nextcloud.safedc.services
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default

  cron:
    image: jakubkrzywda/nextcloud:${NEXTCLOUD_VERSION}
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

  smtp-server:
    image: namshi/smtp
    restart: always

volumes:
  db:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
